CREATE DATABASE LIVRARIA; #cria o banco de dados;

USE LIVRARIA; #conecta ao banco, para poder realizar as funcoes;

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAGINAS CHAR(3),
	NOME_EDITORA VARCHAR(30),
	VALOR_LIVRO FLOAT,
	ESTADO_EDITORA CHAR(2),
	ANO_PUBLICACAO CHAR(4)
);

SHOW TABLES; #mostra as tabelas

DESC LIVROS; #mostra as rows da tabela

#inserindo as colunas na tabela

INSERT INTO  LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Cavaleiro Real','Ana Claudia','F','465','Atlas',49.9,'RJ','2009');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('SQL para leigos','João Nunes','M','450','Addison',98,'SP','2018');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Receitas Caseiras','Celia Tavares','F','210','Atlas',45,'RJ','2008');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Pessoas Efetivas','Eduardo Santos','M','390','Beta',78.99,'RJ','2018');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Habitos Saudáveis','Eduardo Santos','M','630','Beta',150.98,'RJ','2019');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('A Casa Marrom','Hermes Macedo','M','250','Bubba',60,'MG','2016');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Estácio Querido','Geraldo Francisco','M','310','Insignia',100,'ES','2015');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Pra sempre amigas','Leda Silva','F','510','Insignia',78.98,'ES','2011');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('Copas Inesqueciveis','Marco Alcantra','M','200','Larson',130.98,'RS','2018');

INSERT INTO	 LIVROS(NOME_LIVRO,NOME_AUTOR,SEXO_AUTOR,NUMERO_PAGINAS,NOME_EDITORA, VALOR_LIVRO, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('O poder da mente','Clara Mafra','F','120','Continental',56.58,'SP','2017');

#verificar se foi inserido corretamente; obs: projeta o conteudo das colunas na tela
#1 – Trazer todos os dados.
SELECT * FROM LIVROS;

#2 – Trazer o nome do livro e o nome da editora.
SELECT NOME_LIVRO,NOME_EDITORA FROM LIVROS;

#3 – Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino.
SELECT NOME_LIVRO,ESTADO_EDITORA FROM LIVROS WHERE SEXO_AUTOR='M';

#4 – Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.
SELECT NOME_LIVRO,NUMERO_PAGINAS FROM LIVROS WHERE SEXO_AUTOR='F';

#5 – Trazer os valores dos livros das editoras de São Paulo.
SELECT VALOR_LIVRO FROM LIVROS WHERE ESTADO_EDITORA='SP';

#6 – Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).
SELECT * FROM LIVROS WHERE SEXO_AUTOR='M' AND ESTADO_EDITORA='SP' OR SEXO_AUTOR='M' AND ESTADO_EDITORA='RJ';