CREATE DATABASE OFICINA;

USE OFICINA;

STATUS

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE #RELACIONAMENTO 1x1, ONDE 1 CLIENTE SO POSSUI 1 CARRO
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
	NUMERO VARCHAR(11) NOT NULL,
	ID_CLIENTE INT #RELACIONAMENTO 1xN, POIS 1 CLIENTE PODE TER MAIS DE UM TELEFONE, LOGO, NÃO É UNIQUE TBM
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE #UNIQUE POIS NÃO POSSO REPETIR O NOME DA MARCA
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT #NAO POSSO USAR UNIQUE, POIS O RELACIONAMENTO É Nx1, LOGO, POSSO TER MAIS DE UM CARRO COM A MESMA MARCA
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR) #UNIAO, E SERIA UMA PK
);

/* CONSTRAINTS */ #CONVENCIONADO DA SEGUINTE FORMA, TIPOKEY_TABELA-ONDE-PERTENCE_TABELA-ONDE-VEIO

ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO) 
REFERENCES CARRO(IDCARRO);

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE) 
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) 
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

#UMA PRIMARY KEY, PODE SER PRIMARY KEY E FOREIGN KEY AO MESMO TEMPO
#A TABELA MAIS FORTE DESSE SISTEMA É A TABELA CARRO

/* DESCRIPTION OF TABLES */

DESC CARRO;
DESC CLIENTE;
DESC COR;
DESC CARRO_COR;
DESC MARCA;
DESC TELEFONE;

/* INSERTING DATA */

INSERT INTO CARRO VALUES(NULL, '1.0', )